// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
extension SFSymbol {
    internal static var localizationsAvailableSince2_2: [SFSymbol : Set<Localization>] {
        [
            airpodsmax: [],
            applewatchSideRight: [],
            characterBubble: [.ar, .he],
            characterBubbleFill: [.ar, .he],
            characterCursorIbeam: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            characterTextbox: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            hifispeakerAndHomepodmini: [],
            hifispeakerAndHomepodminiFill: [],
            homepodAndHomepodmini: [],
            homepodAndHomepodminiFill: [],
            homepodmini: [],
            homepodmini2: [],
            homepodmini2Fill: [],
            homepodminiFill: [],
            rectangleTopthirdInsetFill: []
        ]
    }

    internal static var symbolsDeprecatedSince2_2: Set<SFSymbol> {
        [
            rectangleTopthirdInset,
            tBubble,
            tBubbleFill,
            textCursor,
            textbox
        ]
    }
}
