// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
extension SFSymbol {
    internal static var localizationsAvailableSince3_1: [SFSymbol : Set<Localization>] {
        [
            boltRingClosed: [],
            platterFilledBottomAndArrowDownIphone: [],
            platterFilledBottomIphone: [],
            platterFilledTopAndArrowUpIphone: [],
            platterFilledTopIphone: [],
            square3Layers3dDownBackward: [],
            square3Layers3dDownForward: [],
            square3Layers3dDownLeft: [],
            square3Layers3dDownRight: [],
            textJustifyLeading: [],
            textJustifyLeft: [],
            textJustifyRight: [],
            textJustifyTrailing: []
        ]
    }

    internal static var symbolsDeprecatedSince3_1: Set<SFSymbol> {
        [
            textJustifyleft,
            textJustifyright
        ]
    }
}
