// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 3.3 Symbols
@available(iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5, *)
public extension SFSymbol {
    /// 􁂂
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let cameraMacro = SFSymbol(rawValue: "camera.macro")

    /// 􁂃
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let cameraMacroCircle = SFSymbol(rawValue: "camera.macro.circle")

    /// 􁂄
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let cameraMacroCircleFill = SFSymbol(rawValue: "camera.macro.circle.fill")

    /// 􁑢
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let dotsAndLineVerticalAndCursorarrowRectangle = SFSymbol(rawValue: "dots.and.line.vertical.and.cursorarrow.rectangle")

    /// 􁎕
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let keyViewfinder = SFSymbol(rawValue: "key.viewfinder")

    /// 􁏺
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to creating or signing in with a passkey.
    static let personBadgeKey = SFSymbol(rawValue: "person.badge.key")

    /// 􁎨
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to creating or signing in with a passkey.
    static let personBadgeKeyFill = SFSymbol(rawValue: "person.badge.key.fill")
}
