// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 1.1 Symbols
@available(iOS 13.1, macOS 11.0, tvOS 13.0, watchOS 6.1, *)
public extension SFSymbol {
    /// 􀞸
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let arrowUturnLeftCircleBadgeEllipsis = SFSymbol(rawValue: "arrow.uturn.left.circle.badge.ellipsis")

    /// 􀞖
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let aspectratio = SFSymbol(rawValue: "aspectratio")

    /// 􀞏
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let aspectratioFill = SFSymbol(rawValue: "aspectratio.fill")

    /// 􀙘
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let car = SFSymbol(rawValue: "car")

    /// 􀞾
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let circleGrid2x2 = SFSymbol(rawValue: "circle.grid.2x2")

    /// 􀞿
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let circleGrid2x2Fill = SFSymbol(rawValue: "circle.grid.2x2.fill")

    /// 􀝌
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let flashlightOffFill = SFSymbol(rawValue: "flashlight.off.fill")

    /// 􀞋
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let flashlightOnFill = SFSymbol(rawValue: "flashlight.on.fill")

    /// 􀞒
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    @available(iOS, introduced: 13.1, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(macOS, introduced: 11.0, deprecated: 11.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(tvOS, introduced: 13.0, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    @available(watchOS, introduced: 6.1, deprecated: 7.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRight")
    static let flipHorizontal = SFSymbol(rawValue: "flip.horizontal")

    /// 􀞓
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    @available(iOS, introduced: 13.1, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(macOS, introduced: 11.0, deprecated: 11.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(tvOS, introduced: 13.0, deprecated: 14.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    @available(watchOS, introduced: 6.1, deprecated: 7.0, renamed: "arrowLeftAndRightRighttriangleLeftRighttriangleRightFill")
    static let flipHorizontalFill = SFSymbol(rawValue: "flip.horizontal.fill")

    /// 􀜇
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let mappinCircle = SFSymbol(rawValue: "mappin.circle")

    /// 􀜈
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor (iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0)
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let mappinCircleFill = SFSymbol(rawValue: "mappin.circle.fill")

    /// 􀒔
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let paperclipCircle = SFSymbol(rawValue: "paperclip.circle")

    /// 􀒕
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let paperclipCircleFill = SFSymbol(rawValue: "paperclip.circle.fill")

    /// 􀒴
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let pinCircle = SFSymbol(rawValue: "pin.circle")

    /// 􀒵
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Multicolor (iOS 14.0, macOS 11.0, tvOS 14.0, watchOS 7.0)
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let pinCircleFill = SFSymbol(rawValue: "pin.circle.fill")

    /// 􀞷
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let scissorsBadgeEllipsis = SFSymbol(rawValue: "scissors.badge.ellipsis")

    /// 􀑔
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let studentdesk = SFSymbol(rawValue: "studentdesk")
}
