// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

@available(iOS 14.2, macOS 11.0, tvOS 14.2, watchOS 7.1, *)
extension SFSymbol {
    internal static var localizationsAvailableSince2_1: [SFSymbol : Set<Localization>] {
        [
            aqiHigh: [],
            aqiLow: [],
            aqiMedium: [],
            brazilianrealsignCircle: [],
            brazilianrealsignCircleFill: [],
            brazilianrealsignSquare: [],
            brazilianrealsignSquareFill: [],
            cartCircle: [],
            cartCircleFill: [],
            character: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            characterBookClosed: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            characterBookClosedFill: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            clockArrow2Circlepath: [],
            directcurrent: [],
            docTextBelowEcg: [.rtl],
            docTextBelowEcgFill: [.rtl],
            exclamationmarkApplewatch: [],
            infinityCircle: [],
            infinityCircleFill: [],
            ipadBadgePlay: [],
            ipadHomebuttonBadgePlay: [],
            ipadHomebuttonLandscapeBadgePlay: [],
            ipadLandscapeBadgePlay: [],
            iphoneBadgePlay: [],
            iphoneHomebuttonBadgePlay: [],
            iphoneHomebuttonLandscape: [],
            iphoneLandscape: [],
            ipodtouchLandscape: [],
            lockApplewatch: [],
            photoTv: [],
            playTv: [],
            playTvFill: [],
            rectangleBadgePersonCrop: [],
            rectangleFillBadgePersonCrop: [],
            rectangleTopthirdInset: [],
            repeat1Circle: [],
            repeat1CircleFill: [],
            repeatCircle: [],
            repeatCircleFill: [],
            shieldCheckerboard: [],
            shuffleCircle: [],
            shuffleCircleFill: [],
            textBelowPhoto: [.rtl],
            textBelowPhotoFill: [.rtl],
            textCursor: [.zhTraditional],
            textbox: [.zhTraditional],
            textformatSize: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            textformatSizeLarger: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            textformatSizeSmaller: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            textformatSubscript: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            textformatSuperscript: [.ar, .he, .hi, .ja, .ko, .th, .zh, .zhTraditional],
            torus: [],
            tvAndMediabox: []
        ]
    }

    internal static var symbolsDeprecatedSince2_1: Set<SFSymbol> {
        []
    }
}
