// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 2.2 Symbols
@available(iOS 14.5, macOS 11.3, tvOS 14.5, watchOS 7.4, *)
public extension SFSymbol {
    /// 􀺹
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s AirPods Max.
    static let airpodsmax = SFSymbol(rawValue: "airpodsmax")

    /// 􀸎
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple Watch.
    static let applewatchSideRight = SFSymbol(rawValue: "applewatch.side.right")

    /// 􀌰
    /// 9 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Hebrew
    /// - Chinese (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Hindi (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Japanese (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Korean (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Thai (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Traditional Chinese (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let characterBubble = SymbolWith8Localizations<Ar, He, Hi_v3, Ja_v3, Ko_v3, Th_v3, ZhTraditional_v3, Zh_v3>(rawValue: "character.bubble")

    /// 􀌱
    /// 9 Localizations, 3 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Hebrew
    /// - Chinese (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Hindi (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Japanese (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Korean (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Thai (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Traditional Chinese (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let characterBubbleFill = SymbolWith8Localizations<Ar, He, Hi_v3, Ja_v3, Ko_v3, Th_v3, ZhTraditional_v3, Zh_v3>(rawValue: "character.bubble.fill")

    /// 􀅫
    /// 9 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let characterCursorIbeam = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "character.cursor.ibeam")

    /// 􀅶
    /// 9 Localizations, 2 Layersets
    ///
    /// Localizations:
    /// - Latin
    /// - Arabic
    /// - Chinese
    /// - Hebrew
    /// - Hindi
    /// - Japanese
    /// - Korean
    /// - Thai
    /// - Traditional Chinese
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    static let characterTextbox = SymbolWith8Localizations<Ar, He, Hi, Ja, Ko, Th, Zh, ZhTraditional>(rawValue: "character.textbox")

    /// 􀷭
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let hifispeakerAndHomepodmini = SFSymbol(rawValue: "hifispeaker.and.homepodmini")

    /// 􀷮
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let hifispeakerAndHomepodminiFill = SFSymbol(rawValue: "hifispeaker.and.homepodmini.fill")

    /// 􀷫
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod and HomePod mini.
    static let homepodAndHomepodmini = SFSymbol(rawValue: "homepod.and.homepodmini")

    /// 􀷬
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod and HomePod mini.
    static let homepodAndHomepodminiFill = SFSymbol(rawValue: "homepod.and.homepodmini.fill")

    /// 􀷧
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let homepodmini = SFSymbol(rawValue: "homepodmini")

    /// 􀷩
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let homepodmini2 = SFSymbol(rawValue: "homepodmini.2")

    /// 􀷪
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let homepodmini2Fill = SFSymbol(rawValue: "homepodmini.2.fill")

    /// 􀷨
    /// Single Localization, 2 Layersets, ⚠️ Restricted
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    ///
    /// - Warning: ⚠️ This symbol may not be modified and may only be used to refer to Apple’s HomePod mini.
    static let homepodminiFill = SFSymbol(rawValue: "homepodmini.fill")

    /// 􀴊
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical (iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0)
    @available(iOS, introduced: 14.5, deprecated: 15.0, renamed: "rectangleTopthirdInsetFilled")
    @available(macOS, introduced: 11.3, deprecated: 12.0, renamed: "rectangleTopthirdInsetFilled")
    @available(tvOS, introduced: 14.5, deprecated: 15.0, renamed: "rectangleTopthirdInsetFilled")
    @available(watchOS, introduced: 7.4, deprecated: 8.0, renamed: "rectangleTopthirdInsetFilled")
    static let rectangleTopthirdInsetFill = SFSymbol(rawValue: "rectangle.topthird.inset.fill")
}
