// Don't touch this manually, this code is generated by the SymbolsGenerator helper tool

// 3.1 Symbols
@available(iOS 15.1, macOS 12.0, tvOS 15.1, watchOS 8.1, *)
public extension SFSymbol {
    /// 􁉘
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let boltRingClosed = SFSymbol(rawValue: "bolt.ring.closed")

    /// 􁋂
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let platterFilledBottomAndArrowDownIphone = SFSymbol(rawValue: "platter.filled.bottom.and.arrow.down.iphone")

    /// 􁋀
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let platterFilledBottomIphone = SFSymbol(rawValue: "platter.filled.bottom.iphone")

    /// 􁋁
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let platterFilledTopAndArrowUpIphone = SFSymbol(rawValue: "platter.filled.top.and.arrow.up.iphone")

    /// 􁊿
    /// Single Localization, 2 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    static let platterFilledTopIphone = SFSymbol(rawValue: "platter.filled.top.iphone")

    /// 􁋜
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let square3Layers3dDownBackward = SFSymbol(rawValue: "square.3.layers.3d.down.backward")

    /// 􁋛
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let square3Layers3dDownForward = SFSymbol(rawValue: "square.3.layers.3d.down.forward")

    /// 􁉼
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let square3Layers3dDownLeft = SFSymbol(rawValue: "square.3.layers.3d.down.left")

    /// 􁉽
    /// Single Localization, 3 Layersets
    ///
    /// Layersets:
    /// - Monochrome
    /// - Hierarchical
    /// - Multicolor (iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0)
    static let square3Layers3dDownRight = SFSymbol(rawValue: "square.3.layers.3d.down.right")

    /// 􁉀
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let textJustifyLeading = SFSymbol(rawValue: "text.justify.leading")

    /// 􀌄
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let textJustifyLeft = SFSymbol(rawValue: "text.justify.left")

    /// 􀌅
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let textJustifyRight = SFSymbol(rawValue: "text.justify.right")

    /// 􁉁
    /// Single Localization, Single Layerset
    ///
    /// Layersets:
    /// - Monochrome
    static let textJustifyTrailing = SFSymbol(rawValue: "text.justify.trailing")
}
